Feature/jwt
TirusTimes/tirus-times-back pull request #5
Opened 2022-12-04 13:28 UTC by HurleySA

## Description

Adding JWT to application using jsonwebtoken lib.

## Related Issues

[Use keywords like 'close' or 'solves' to link this PR to an issue.
For example:

Closes #12345
Unblocks #54321](https://trello.com/c/vbe6Oemv/12-cria%C3%A7%C3%A3o-de-jwt-no-backend-para-autentica%C3%A7%C3%A3o)

## Progress

Use checkboxes to show that you did and what you have to do. For example:

- [x] New endpoint created;
- [x ] New folder to Middlewares
- [ X] Authetication running

## How to test it

The authetication is only applied on the Put Route: http://localhost:3333/api/users

To request this endpoint is necessary to put Authorization on Header. Create a new Authorization Token using route: http://localhost:3333/api/auth, passing {username, password}

## Visual reference

Please include screenshots, gifs or recordings

## Change logs

Change logs are important to keep trace of what was changed

2022-12-13 22:30 UTC, viniciuslacerda0 commented on .env
> +SECRET='IOaheihEOHaAOIEHaiohIOEHaioh'
Não suba o .env no projeto

2022-12-13 22:34 UTC, viniciuslacerda0 commented on src/controllers/AuthControler.ts
> +        delete user.password;
Quando testamos de tarde, estava mostrando a senha, tenta criar um objeto sem esse dado

2022-12-14 13:00 UTC, gustavolbs requested changes

2022-12-14 13:00 UTC, gustavolbs commented on .env
> +SECRET='IOaheihEOHaAOIEHaiohIOEHaioh'
@HurleySA edita o commit fd77c88a05a0c42295e80b170874c66de0f7dbe9 removendo o arquivo `.env` e adiciona o `.env` no `.gitignore`

2022-12-14 13:00 UTC, gustavolbs commented on .gitignore
> +.env
Essa mudança precisa ser feita junto ao commit fd77c88a05a0c42295e80b170874c66de0f7dbe9, senão o `.env` vai subir.

2022-12-14 13:00 UTC, gustavolbs commented on .env.example
> +DATABASE_URL=postgresql://tirusTimes:1234@localhost:5432/prisma-postgres?schema=public
```suggestion
SECRET=
DATABASE_URL=
```

2022-12-14 13:00 UTC, gustavolbs commented on package.json
> +    "@types/jsonwebtoken": "^8.5.9",
Types normalmente devem ser utilizados como devDependencies. Tem certeza q elas são necessárias como `dependencies` e não como `devDependencies`.

2022-12-14 13:00 UTC, gustavolbs commented on src/helpers/schemas.ts
>  const schemaCreate = Yup.object().shape({
```suggestion
const schemaCreateUser = Yup.object().shape({
```

2022-12-14 13:00 UTC, gustavolbs commented on src/helpers/schemas.ts
> +const schemaUpdate = Yup.object().shape({
```suggestion
const schemaUpdateUser = Yup.object().shape({
```

2022-12-17 11:20 UTC, viniciuslacerda0 approved these changes

2022-12-19 17:26 UTC, closed without merging