feat: add group crud
TirusTimes/tirus-times-back pull request #6
Opened 2022-12-06 13:19 UTC by higorrfa

## Description

Create a CRUD to groups

## Related Issues

https://trello.com/c/c7KZHwfb/31-crud-de-grupos

## Progress

- [x] New endpoints created;

## How to test it

Test the endpoints in http://localhost:3333/api

## Visual reference

![image](https://user-images.githubusercontent.com/29640804/205918382-a9bec412-1ef6-44d1-aff1-b1904c9dac74.png)
![image](https://user-images.githubusercontent.com/29640804/205918500-5970d6fb-3be4-46bf-8ca6-b3a155d344cd.png)
![image](https://user-images.githubusercontent.com/29640804/205918676-a3efd5a0-94a9-4f33-91c3-7ff444ed3c22.png)
![image](https://user-images.githubusercontent.com/29640804/205918742-f60391ac-8e33-4a03-8926-93a143a2e9c5.png)
![image](https://user-images.githubusercontent.com/29640804/205918853-3ab9186f-e524-44ef-987f-e35e263302f2.png)
![image](https://user-images.githubusercontent.com/29640804/205919120-b2bed9cd-e870-4d9b-b0be-8684cb608ada.png)

## Change logs

Creation of group CRUD and its respective services

2022-12-06 22:15 UTC, gustavolbs requested changes
Dá uma olhada nos retornos dos erros. Tem repetição em série dos erros (basicamente todo método retorna a msm coisa).

2022-12-06 22:15 UTC, gustavolbs commented on src/controllers/groupController.ts
> +        .json({ error: errorMessage });
```suggestion
      return response
        .status(StatusCodes.INTERNAL_SERVER_ERROR)
        .json({ error: err.message ? err.message : 'Failed to do something exceptional' });
```

Isso n funciona n?

2022-12-06 22:15 UTC, gustavolbs commented on src/controllers/groupController.ts
> +const groupServiceInstance = new GroupService();
Insere uma linha aqui entre os imports e a const

2022-12-06 22:15 UTC, gustavolbs commented on src/controllers/userController.ts
> +  async getAllGroups(request: Request, response: Response): Promise<Response> {
Se esse método retornar todos os grupos que o usuário está, eu sugiro que seja renomeado pra `getAllUserGroups` ou algo assim.

2022-12-06 22:15 UTC, gustavolbs commented on src/helpers/dto.ts
> +}
Sou leigo em backend. Pergunta: Não era pra ter um array de users ou algo assim em cada grupo não? Pelo menos ao meu ver, todo grupo quando criado tem uma lista de usuários que começa com o user ou vazia e adiciona o user.

2022-12-06 22:15 UTC, gustavolbs commented on src/services/groupService.ts
> +const userServiceInstance = new UserService();
Insere uma linha entre os imports e a const, por favor.

2022-12-06 22:22 UTC, higorrfa commented on src/helpers/dto.ts
> +}
Creio que não há necessidade, a tabela de relacionamento UserGroup já explicita qual usuário está em qual grupo.

2022-12-11 02:08 UTC, viniciuslacerda0 commented on src/services/groupService.ts
> +        id: Number(id)
se você já deixa explicito que o id vai ser Number no parâmetro da função, não tem necessidade do cast pra Number nesses where!

2022-12-11 02:09 UTC, viniciuslacerda0 commented on src/services/groupService.ts
> +        groupId: Number(groupId)
Ditto

2022-12-11 02:09 UTC, viniciuslacerda0 commented on src/services/userService.ts
> +  async verifyIfExists(id: Number) {
Ditto para esse arquivo também!

2022-12-18 02:47 UTC, higorrfa commented on src/services/groupService.ts
> +        id: Number(id)
![image](https://user-images.githubusercontent.com/29640804/208278896-15d54b17-f7bf-42d3-92dc-8c5fb4923845.png)
sem o cast dá esse erro

2022-12-18 10:47 UTC, viniciuslacerda0 approved these changes

2022-12-20 01:47 UTC, gustavolbs requested changes
Dá uma olhada nas conversations abertas.

BTW, não se fecha conversations sem comentar a resolução tomada para a thread ou sem seguir o sugerido.

2022-12-20 01:47 UTC, gustavolbs commented on src/services/groupService.ts
> +const userServiceInstance = new UserService();
```suggestion
import { groupSchemaCreate } from '../helpers/schemas';

const userServiceInstance = new UserService();
```

2022-12-20 01:47 UTC, gustavolbs commented on src/services/groupService.ts
> +        id: Number(id)
@viniciuslacerda0 👆

2022-12-20 01:47 UTC, gustavolbs commented on src/services/groupService.ts
> +        groupId: Number(groupId)
@viniciuslacerda0 👆

2022-12-20 01:47 UTC, gustavolbs commented on src/services/userService.ts
> +  async verifyIfExists(id: Number) {
@viniciuslacerda0 👆

2022-12-20 01:47 UTC, gustavolbs commented on src/controllers/groupController.ts
> +        .json({ error: errorMessage });
No pior dos casos, caso o sugerido não funcione:

```suggestion
      return response
	        .status(StatusCodes.INTERNAL_SERVER_ERROR)
	        .json({ error: err instanceof Error ? err.message : 'Failed to do something exceptional'
```

2022-12-20 13:47 UTC, viniciuslacerda0 commented
Eu roubei o PR do @higorrfa. @gustavolbs arrumei as coisas e aproveitei e arrumei o resto do projeto que tinha umas cagadas

2022-12-20 14:28 UTC, gustavolbs approved these changes

2022-12-20 14:28 UTC, gustavolbs commented on src/controllers/groupController.ts
> +    }
Pela quantidade de repetições disso, fica claro q a gente pode, futuramente, mover tudo isso pra um método e só dar um return nele passando o necessário.

2022-12-20 14:40 UTC, viniciuslacerda0 commented on src/controllers/groupController.ts
> +    }
Eu penso que devemos ajustar isso depois pra usar o StatusCodes correto também

2022-12-20 14:40 UTC, merged